### ISSUE TITLE
#### Cannot load fast pose extraction, switched to legacy slow implementation. ####

### ISSUE THREAD

**Issue by ccl-private** [Daniil-Osokin/lightweight-human-pose-estimation-3d-demo.pytorch#37]
how to load fast pose extraction?

**Comment by Daniil-Osokin** [comment]
Hi! To use fast pose extractor, please follow [prerequisites](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation-3d-demo.pytorch#prerequisites), mainly successfully run `setup.py build_ext` and add result to `PYTHONPATH`.

**Comment by ccl-private** [comment]
thanks~I forget that~

**Comment by Fan-loewe** [comment]
Hi,

I want to use the fast pose extractor in ROS, I successfully built the setup.py and add the result to PYTHONPATH.
when I run sys.path, it is able to show the path
'/home/aegis/catkin_ws/src/pose_estimation/src/pose_estimation/pose_extractor/build'

I could "import pose_extractor" successfully, but it fails when "from pose_extractor import extract_poses".

Does that mean C++ library was not imported to python interface? 

Thanks!!

**Comment by Daniil-Osokin** [comment]
Hi, do you have `pose_extractor.so` inside `pose_extractor/build` folder? If so, what is the output of (should be something like `00000000000030c0 `**t**` _ZL13extract_posesP7_objectS0_`):
```
nm pose_extractor/build/pose_extractor.so | grep extract_poses
```
I have just export to PYTHONPATH and demo works (got +10 FPS):
```
~/lightweight-human-pose-estimation-3d-demo.pytorch$ export PYTHONPATH=./pose_extractor/build/:$PYTHONPATH
~/lightweight-human-pose-estimation-3d-demo.pytorch$ python demo.py -m ~/Downloads/human-pose-estimation-3d.pth --video 0
```

**Comment by Fan-loewe** [comment]
Hi, yes I have pose_extractor.so inside, the output shows:
00000000000032a8 t _ZL13extract_posesP7_objectS0_

Originally the demo also works on me. When I apply into ROS, I need to recompile demo.python with catkin make. I think I could not access this build folder in my catkin workspace even if it already in my python environment. What is the mechanism to link the .so file?

**Comment by Daniil-Osokin** [comment]
It looks like things work in a different way in ROS, you can check [this tutorial](http://wiki.ros.org/ROS/Tutorials/Using%20a%20C%2B%2B%20class%20in%20Python), it has steps to wrap C++ function under ROS to call in Python. Or may be some other recipes will work (I do not have a ROS to check).

**Comment by Fan-loewe** [comment]
Hi Daniil, it works now. Thanks!

**Comment by Daniil-Osokin** [comment]
Great! Can you please tell what was helped or may be attach a diff with changes for the future readers (and me :), it is really interesting how code should be transformed for ROS)?

**Comment by Fan-loewe** [comment]
Sure, my pleasure!

I referred this tutorial. https://roboticsbackend.com/ros-import-python-module-from-another-package/
I first build the fast extraction C++ wrapper pose_extractor, then export the python modules into ROS.

My package are built as follows:
<pre>pose_estimation/
└── src
    └── pose_estimation
         ├── __init__.py
         ├── data
         ├── models
         ├── modules
         └── pose_extractor
├── CMakeLists.txt
├── package.xml
├── setup.py
└── demo.py
</pre>
With such set up of my package,  "pose_estimation" need to be added as a prefix when importing the packages. For example:
from pose_estimation.modules.input_reader import VideoReader, ImageReader

We need to pay extra attention when import pose_extractor (the fast version)
1. If you want to export the python path in code, use sys.path.insert instead of sys.path.append. (I don't quite know the reason, but the latter one cannot work)
2.  In the parses_poses.py, use from pose_extractor import extract_poses instead of from pose_estimation.pose_extractor import extract_poses.

Hope it helps.

**Comment by Daniil-Osokin** [comment]
Many thanks for the clarifications!
